"use strict"; return ((function() {
  const { core } = __bootstrap;
  const { promises } = core.loadExtScript("ext:deno_node/dns.ts");
  return {
    default: promises,
    getDefaultResultOrder: promises.getDefaultResultOrder,
    getServers: promises.getServers,
    lookup: promises.lookup,
    lookupService: promises.lookupService,
    resolve: promises.resolve,
    resolve4: promises.resolve4,
    resolve6: promises.resolve6,
    resolveAny: promises.resolveAny,
    resolveCaa: promises.resolveCaa,
    resolveCname: promises.resolveCname,
    resolveMx: promises.resolveMx,
    resolveNaptr: promises.resolveNaptr,
    resolveNs: promises.resolveNs,
    resolvePtr: promises.resolvePtr,
    Resolver: promises.Resolver,
    resolveSoa: promises.resolveSoa,
    resolveSrv: promises.resolveSrv,
    resolveTxt: promises.resolveTxt,
    reverse: promises.reverse,
    setDefaultResultOrder: promises.setDefaultResultOrder,
    setServers: promises.setServers,
    NODATA: promises.NODATA,
    FORMERR: promises.FORMERR,
    SERVFAIL: promises.SERVFAIL,
    NOTFOUND: promises.NOTFOUND,
    NOTIMP: promises.NOTIMP,
    REFUSED: promises.REFUSED,
    BADQUERY: promises.BADQUERY,
    BADNAME: promises.BADNAME,
    BADFAMILY: promises.BADFAMILY,
    BADRESP: promises.BADRESP,
    CONNREFUSED: promises.CONNREFUSED,
    TIMEOUT: promises.TIMEOUT,
    EOF: promises.EOF,
    FILE: promises.FILE,
    NOMEM: promises.NOMEM,
    DESTRUCTION: promises.DESTRUCTION,
    BADSTR: promises.BADSTR,
    BADFLAGS: promises.BADFLAGS,
    NONAME: promises.NONAME,
    BADHINTS: promises.BADHINTS,
    NOTINITIALIZED: promises.NOTINITIALIZED,
    LOADIPHLPAPI: promises.LOADIPHLPAPI,
    ADDRGETNETWORKPARAMS: promises.ADDRGETNETWORKPARAMS,
    CANCELLED: promises.CANCELLED
  };
})());